body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit your Polaris dataset for review!
  - type: input
    id: polaris-link
    attributes:
      label: Polaris Link
      description: Please share the link to your public dataset on Polaris.
    validations:
      required: true
  - type: textarea
    id: readme
    attributes:
      label: README
      description: Please share more information about the data generation process and the relevance of this dataset to drug discovery.
    validations:
      required: true
  - type: input
    id: dataset-source
    attributes:
      label: Dataset Source
      description: Please share a reference to the source (e.g. PDBBind, Chembl, a DOI, ...). 
    validations:
      required: true
  - type: input
    id: dataset-curation
    attributes:
      label: Dataset Curation
      description: Please share a reference to a public, reproducible piece of code to recreate the dataset from the source data.
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Dataset Completeness
      description: The [Polaris Dataset class](https://github.com/polaris-hub/polaris/blob/main/polaris/dataset/_dataset.py#L45) includes dedicated fields to share the above information with the community.
      options:
        - label: I confirm that I filled out at least the `readme`, `source` and `curation_reference` fields for my Polaris dataset.
          required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Anything else we should know?
      description: Please share any additional context you think may be important for the vetting process.
